version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toma-turno-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - toma-turno-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: toma-turno-db
    environment:
      - POSTGRES_USER=labsis
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=toma_turno
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - toma-turno-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labsis"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: toma-turno-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - toma-turno-network

volumes:
  postgres_data:

networks:
  toma-turno-network:
    driver: bridge